### ISSUE TITLE
the 

### ISSUE THREAD

**Issue by Joyce500** [mdozmorov/gwas2bed#1]
Hi Mikhail, the hudine web interface dose not respond now. 
So I'd like to ask if you have the raw data from http://barabasilab.neu.edu/projects/hudine/resource/data/data.html  ?   
I'm very anxious to get the data.

**Comment by mdozmorov** [comment]
Here's what I have https://www.dropbox.com/s/fvucmdmyyy5xxvc/AllNet3.net.gz?dl=0

**Comment by Joyce500** [comment]
This is very helpful! Thank you very much!
